services:
  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env # POSTGRES_USER and POSTGRES_PASSWORD
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:cached # improves performance on macOS by using cached file metadata
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      RAILS_ENV: development
    command: bundle exec rails server -b 0.0.0.0 -p 3000
volumes:
  postgres_data:
