# Use the official Ruby image as a parent image
FROM ruby:3.2.2

# Install dependencies
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs yarn

# Set the working directory
WORKDIR /app

# Copy the Gemfile and Gemfile.lock
COPY Gemfile Gemfile.lock /app/

# Install the gems
RUN bundle install

# Copy the rest of the application code
COPY . /app

# Expose port 3000 to the Docker host
EXPOSE 3000