default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>

test:
  <<: *default
  # database: bookscape_test
  database: <%= ENV["POSTGRES_DB"] + '_test' %>


production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>
